{% set name = "laspy" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81940b2d6dbcf1746173bf11fc28e960742bc22de30a975f9ec44d7b32826d39

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - numpy
    - lazrs-python
  run:
    - python
    - numpy
    - lazrs-python

test:
  imports:
    - laspy
  requires:
    - pytest
  source_files:
    - tests/*
  commands:
    - pytest -v

about:
  home: https://github.com/laspy/laspy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Native Python ASPRS LAS read/write library

  description: |
    Laspy is a python library for reading, modifying and creating LAS LiDAR files.
  doc_url: https://laspy.readthedocs.io/en/latest/
  dev_url: https://github.com/laspy/laspy

extra:
  recipe-maintainers:
    - plimkilde
    - hobu
    - chambbj
