{% set name = "laspy" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f56feb5445e75d6ff12ee814aab6a35339290e75264ff277c6bf553f3025a3f5

build:
  number: 0
  skip: true  # [python_impl == 'pypy']

  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                            # [build_platform != target_platform]
  host:
    - python
    - pip
    - numpy
    - lazrs-python
    - setuptools
    - m2r2
    - hatch
  run:
    - python
    - numpy
    - lazrs-python
    - m2r2

test:
  imports:
    - laspy
  requires:
    - pytest
  source_files:
    - tests/*
  commands:
    - pytest -v

about:
  home: https://github.com/laspy/laspy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Native Python ASPRS LAS read/write library

  description: |
    Laspy is a python library for reading, modifying and creating LAS LiDAR files.
  doc_url: https://laspy.readthedocs.io/en/latest/
  dev_url: https://github.com/laspy/laspy

extra:
  recipe-maintainers:
    - plimkilde
    - hobu
    - chambbj
